const NON_EXISTENT = 404;
const DEFAULT_ERROR = 500;
const INVALID_DATA = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const CONFLICT = 409;

module.exports = {NON_EXISTENT,
    DEFAULT_ERROR,
    INVALID_DATA,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT};
